name: Question
description: Ask a question about ProfMatch
title: "[Question]: "
labels: ["question"]
body:
  - type: markdown
    attributes:
      value: |
        Have a question? We're here to help! Please provide as much detail as possible.

  - type: textarea
    id: question
    attributes:
      label: Your Question
      description: What would you like to know?
      placeholder: How do I...? Why does...? Can I...?
    validations:
      required: true

  - type: dropdown
    id: category
    attributes:
      label: Category
      description: What area does your question relate to?
      options:
        - Installation & Setup
        - Usage & Features
        - API & Integration
        - Configuration
        - Contributing
        - Other
    validations:
      required: true

  - type: textarea
    id: context
    attributes:
      label: Additional Context
      description: Add any context that might help us answer your question.
      placeholder: |
        I'm trying to...
        I've already tried...
        My setup is...
    validations:
      required: false

  - type: checkboxes
    id: terms
    attributes:
      label: Before Submitting
      description: Please confirm the following
      options:
        - label: I have searched existing issues and discussions
          required: true
        - label: I have reviewed the documentation (README, CONTRIBUTING)
          required: true